
USE shanggang;
DROP TABLE IF EXISTS ship;

CREATE TABLE `ship`(
	`MMSI` int(11) unsigned NOT NULL AUTO_INCREMENT,
	`SHIP_NAME` varchar(100) NOT NULL,
	`IMO` int(11) NOT NULL,
	`LENGTH` DOUBLE unsigned NOT NULL,
	`WIDTH` DOUBLE unsigned NOT NULL,
	`SHIPTYPE` varchar(100) NOT NULL,
	`CAPACITY` DOUBLE unsigned NOT NULL,
	`FLEET_ID` INT(11) unsigned NOT NULL,
	`AREA_ID` varchar(100) NOT NULL,
	PRIMARY KEY (`MMSI`),
	CONSTRAINT `fk_area` FOREIGN KEY (`AREA_ID`) REFERENCES `dumping_area` (`area_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  	CONSTRAINT `fk_fleet` FOREIGN KEY (`FLEET_ID`) REFERENCES `fleet` (`fleet_id`) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 |